substitutions:
  _TELEGRAM_BOT_TOKEN: $_TELEGRAM_BOT_TOKEN
  _WEBHOOK_URL: $_WEBHOOK_URL
  _WEBHOOK_PATH: /webhook
  _OPENAI_API_KEY: $_OPENAI_API_KEY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/telegrambot', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'telegrambot'
      - '--image'
      - 'gcr.io/$PROJECT_ID/telegrambot'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'TELEGRAM_BOT_TOKEN=$_TELEGRAM_BOT_TOKEN,WEBHOOK_URL=$_WEBHOOK_URL,WEBHOOK_PATH=$_WEBHOOK_PATH,OPENAI_API_KEY=$_OPENAI_API_KEY'